##### Numpy Important:

In [1]:
import numpy as np

np.random.randint(1,100,5)

array([65, 96, 53, 53, 70])

In [6]:
np.random.seed(10)
np.random.rand(2,2)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388]])

In [7]:
print(np.arange(10))
np.arange(1,10)

[0 1 2 3 4 5 6 7 8 9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [23]:
x = np.random.rand(10)
y = np.random.rand(10)
[x,y]

[array([0.55757819, 0.56550702, 0.47513225, 0.29279798, 0.06425106,
        0.97881915, 0.33970784, 0.49504863, 0.97708073, 0.44077382]),
 array([0.31827281, 0.51979699, 0.57813643, 0.85393375, 0.06809727,
        0.46453081, 0.78194912, 0.71860281, 0.58602198, 0.03709441])]

In [24]:
np.column_stack([x,y])

array([[0.55757819, 0.31827281],
       [0.56550702, 0.51979699],
       [0.47513225, 0.57813643],
       [0.29279798, 0.85393375],
       [0.06425106, 0.06809727],
       [0.97881915, 0.46453081],
       [0.33970784, 0.78194912],
       [0.49504863, 0.71860281],
       [0.97708073, 0.58602198],
       [0.44077382, 0.03709441]])

##### Pandas

In [10]:
import pandas as pd
df = pd.DataFrame(np.random.randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())
df

W         X         Y         Z
A  0.266070  2.384967  1.123691  1.672622
B  0.099149  1.397996 -0.271248  0.613204
C -0.267317 -0.549309  0.132708 -0.476142
D  1.308473  0.195013  0.400210 -0.337632
E  1.256472 -0.731970  0.660232 -0.350872

In [12]:
df.drop('Z', axis=1)

W         X         Y
A  0.266070  2.384967  1.123691
B  0.099149  1.397996 -0.271248
C -0.267317 -0.549309  0.132708
D  1.308473  0.195013  0.400210
E  1.256472 -0.731970  0.660232

In [13]:
df

W         X         Y         Z
A  0.266070  2.384967  1.123691  1.672622
B  0.099149  1.397996 -0.271248  0.613204
C -0.267317 -0.549309  0.132708 -0.476142
D  1.308473  0.195013  0.400210 -0.337632
E  1.256472 -0.731970  0.660232 -0.350872

In [16]:
print(df.loc['A'])
print(df.iloc[0])

W    0.266070
X    2.384967
Y    1.123691
Z    1.672622
Name: A, dtype: float64
W    0.266070
X    2.384967
Y    1.123691
Z    1.672622
Name: A, dtype: float64


In [17]:
df[df['W']>0]

W         X         Y         Z
A  0.266070  2.384967  1.123691  1.672622
B  0.099149  1.397996 -0.271248  0.613204
D  1.308473  0.195013  0.400210 -0.337632
E  1.256472 -0.731970  0.660232 -0.350872

In [18]:
df[df['W']>0][['Y','X']]

Y         X
A  1.123691  2.384967
B -0.271248  1.397996
D  0.400210  0.195013
E  0.660232 -0.731970

In [19]:
df[(df['W']>0) & (df['Y'] > 1)]

W         X         Y         Z
A  0.26607  2.384967  1.123691  1.672622

In [20]:
df.sort_values(by='X')

W         X         Y         Z
E  1.256472 -0.731970  0.660232 -0.350872
C -0.267317 -0.549309  0.132708 -0.476142
D  1.308473  0.195013  0.400210 -0.337632
B  0.099149  1.397996 -0.271248  0.613204
A  0.266070  2.384967  1.123691  1.672622