In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

### Question-1

##### Learn a model which can classify given data correctly. This is a multiclass data imbalance problem with high dimensions data. You can see the classes are named as n, p1, p2, p3,...So the classes as n are negative ones and with p in it as positive.

In [2]:
#importing the data
data = pd.read_csv('train.csv')
data.head()

0         1         2             3         4         5  \
0 -6.190000e-06 -0.000037  0.000070 -2.560000e-05 -0.000041 -0.000116   
1 -5.080000e-07 -0.000008 -0.000010 -2.900000e-06 -0.000001  0.000046   
2  2.950000e-06  0.000036  0.000004  1.580000e-05  0.000098 -0.000337   
3 -1.680000e-05  0.000026  0.000518  1.550000e-05  0.000072  0.000032   
4  1.610000e-06  0.000018 -0.000156 -9.650000e-07  0.000009  0.000036   

          6         7         8         9  ...       39      40       41  \
0  0.027253  0.027290  0.027220  0.017966  ... -0.69694  1.6505   3.7807   
1  0.031973  0.031981  0.031992 -0.036266  ... -0.49315  9.1182  15.4610   
2  0.010780  0.010744  0.010740 -0.018368  ... -0.68272  1.8947   5.9028   
3 -0.037939 -0.037965 -0.038483 -0.030257  ... -0.71862  1.9076   5.5017   
4  0.010411  0.010393  0.010549 -0.014548  ... -0.71715  1.0778   4.9960   

       42      43      44      45      46      47  48  
0 -1.5016 -1.5017 -1.5016 -1.4939 -1.4939 -1.4940  p4  
1 -1.4980 -1.4980 -1.4980 -1.4978 -1.4978 -1.4978   n  
2 -1.4970 -1.4971 -1.4972 -1.5038 -1.5039 -1.5036  p5  
3 -1.4962 -1.4963 -1.4960 -1.5020 -1.5021 -1.5017  p1  
4 -1.5042 -1.5042 -1.5041 -1.4911 -1.4911 -1.4915  p5  

[5 rows x 49 columns]

In [3]:
# describing the data
data.describe()

0            1            2             3            4  \
count  8507.000000  8507.000000  8507.000000  8.507000e+03  8507.000000   
mean     -0.000001     0.000007     0.000015 -8.104282e-07     0.000010   
std       0.000064     0.000069     0.000230  8.580479e-06     0.000038   
min      -0.000678    -0.002163    -0.002209 -4.170000e-05    -0.000260   
25%      -0.000006    -0.000007    -0.000065 -5.435000e-06    -0.000006   
50%      -0.000002     0.000004     0.000003 -1.740000e-06     0.000004   
75%       0.000002     0.000026     0.000089  3.790000e-06     0.000029   
max       0.005784     0.004525     0.003330  7.080000e-05     0.000348   

                 5            6            7            8            9  ...  \
count  8507.000000  8507.000000  8507.000000  8507.000000  8507.000000  ...   
mean      0.000011     0.015471     0.015463     0.015448    -0.016507  ...   
std       0.000217     0.015712     0.015715     0.015722     0.027911  ...   
min      -0.001626    -0.055309    -0.055316    -0.055328    -0.061243  ...   
25%      -0.000065     0.012665     0.012656     0.012658    -0.035379  ...   
50%       0.000002     0.019684     0.019680     0.019674    -0.028206  ...   
75%       0.000078     0.025535     0.025531     0.025518     0.004998  ...   
max       0.001982     0.046324     0.046319     0.046329     0.071934  ...   

                38           39           40           41           42  \
count  8507.000000  8507.000000  8507.000000  8507.000000  8507.000000   
mean      8.297015    -0.635826     7.031227     8.142438    -1.501420   
std       6.660245     1.607126    11.689025     6.417985     0.003717   
min       0.712110    -0.891000    -0.535610     0.606140    -1.512400   
25%       4.409750    -0.717045     1.500250     4.322250    -1.504100   
50%       6.496200    -0.668240     3.235400     6.343600    -1.500800   
75%       9.822150    -0.578400     7.891750     9.731400    -1.498500   
max      89.372000   146.340000   145.860000    98.758000    -1.458500   

                43           44           45           46           47  
count  8507.000000  8507.000000  8507.000000  8507.000000  8507.000000  
mean     -1.501451    -1.501339    -1.497626    -1.497649    -1.497529  
std       0.003720     0.003670     0.002998     0.002996     0.003015  
min      -1.512400    -1.511800    -1.510400    -1.510400    -1.510500  
25%      -1.504100    -1.504000    -1.499400    -1.499400    -1.499300  
50%      -1.500800    -1.500700    -1.497900    -1.497900    -1.497800  
75%      -1.498500    -1.498500    -1.496100    -1.496100    -1.496000  
max      -1.466200    -1.472600    -1.488400    -1.488400    -1.486800  

[8 rows x 48 columns]

In [4]:
# number of samples and count of each samples
print(f"No. of samples                    :{len(data)}")
print(f"No.of samples with label 'n'      :{len(data[data.iloc[:,48]=='n'])}")
print(f"No.of samples with label 'p1'     :{len(data[data.iloc[:,48]=='p1'])}")
print(f"No.of samples with label 'p2'     :{len(data[data.iloc[:,48]=='p2'])}")
print(f"No.of samples with label 'p3'     :{len(data[data.iloc[:,48]=='p3'])}")
print(f"No.of samples with label 'p4'     :{len(data[data.iloc[:,48]=='p4'])}")
print(f"No.of samples with label 'p5'     :{len(data[data.iloc[:,48]=='p5'])}")

No. of samples                    :8507
No.of samples with label 'n'      :4268
No.of samples with label 'p1'     :853
No.of samples with label 'p2'     :413
No.of samples with label 'p3'     :651
No.of samples with label 'p4'     :1253
No.of samples with label 'p5'     :1069


In [5]:
# dataset is highly imbalanced, so split the data into positive and negative
# all 'pi' labels as positive(1) and all 'n' label as negative(0)
# do binary classification with this dataset
# then split all positive labels in to p1, p2, p3, p4, and p5
# do multilabel classification with this data

###### Data Prepration

In [6]:
#data split into positive and negative labels
data_binary = data.copy()

for i in range(len(data)):
    if data_binary.iloc[i,-1] == 'n':
        data_binary.iloc[i,-1] = 0                 #put n label as 0 and others as 1
    else:
        data_binary.iloc[i,-1] = 1

data_binary.head()

0         1         2             3         4         5  \
0 -6.190000e-06 -0.000037  0.000070 -2.560000e-05 -0.000041 -0.000116   
1 -5.080000e-07 -0.000008 -0.000010 -2.900000e-06 -0.000001  0.000046   
2  2.950000e-06  0.000036  0.000004  1.580000e-05  0.000098 -0.000337   
3 -1.680000e-05  0.000026  0.000518  1.550000e-05  0.000072  0.000032   
4  1.610000e-06  0.000018 -0.000156 -9.650000e-07  0.000009  0.000036   

          6         7         8         9  ...       39      40       41  \
0  0.027253  0.027290  0.027220  0.017966  ... -0.69694  1.6505   3.7807   
1  0.031973  0.031981  0.031992 -0.036266  ... -0.49315  9.1182  15.4610   
2  0.010780  0.010744  0.010740 -0.018368  ... -0.68272  1.8947   5.9028   
3 -0.037939 -0.037965 -0.038483 -0.030257  ... -0.71862  1.9076   5.5017   
4  0.010411  0.010393  0.010549 -0.014548  ... -0.71715  1.0778   4.9960   

       42      43      44      45      46      47  48  
0 -1.5016 -1.5017 -1.5016 -1.4939 -1.4939 -1.4940   1  
1 -1.4980 -1.4980 -1.4980 -1.4978 -1.4978 -1.4978   0  
2 -1.4970 -1.4971 -1.4972 -1.5038 -1.5039 -1.5036   1  
3 -1.4962 -1.4963 -1.4960 -1.5020 -1.5021 -1.5017   1  
4 -1.5042 -1.5042 -1.5041 -1.4911 -1.4911 -1.4915   1  

[5 rows x 49 columns]

In [8]:
# data for multi class classification
# p1=1, p2=2, p3=3, p4=4, p5=5 
data_multi = data[data.iloc[:,-1]!= 'n']       

for i in range(len(data_multi)):
    if data_multi.iloc[i,-1] == 'p1':
        data_multi.iloc[i,-1] = 1
    elif data_multi.iloc[i,-1] == 'p2':
        data_multi.iloc[i,-1] = 2
    elif data_multi.iloc[i,-1] == 'p3':
        data_multi.iloc[i,-1] = 3
    elif data_multi.iloc[i,-1] == 'p4':
        data_multi.iloc[i,-1] = 4
    elif data_multi.iloc[i,-1] == 'p5':
        data_multi.iloc[i,-1] = 5

data_multi.head()

0         1         2             3         4         5         6  \
0 -0.000006 -0.000037  0.000070 -2.560000e-05 -0.000041 -0.000116  0.027253   
2  0.000003  0.000036  0.000004  1.580000e-05  0.000098 -0.000337  0.010780   
3 -0.000017  0.000026  0.000518  1.550000e-05  0.000072  0.000032 -0.037939   
4  0.000002  0.000018 -0.000156 -9.650000e-07  0.000009  0.000036  0.010411   
8 -0.000002 -0.000016  0.000046 -1.330000e-06  0.000008 -0.000092  0.011017   

          7         8         9  ...       39       40       41      42  \
0  0.027290  0.027220  0.017966  ... -0.69694   1.6505   3.7807 -1.5016   
2  0.010744  0.010740 -0.018368  ... -0.68272   1.8947   5.9028 -1.4970   
3 -0.037965 -0.038483 -0.030257  ... -0.71862   1.9076   5.5017 -1.4962   
4  0.010393  0.010549 -0.014548  ... -0.71715   1.0778   4.9960 -1.5042   
8  0.011033  0.010987  0.019514  ... -0.68758  11.5330  30.4150 -1.4991   

       43      44      45      46      47  48  
0 -1.5017 -1.5016 -1.4939 -1.4939 -1.4940   4  
2 -1.4971 -1.4972 -1.5038 -1.5039 -1.5036   5  
3 -1.4963 -1.4960 -1.5020 -1.5021 -1.5017   1  
4 -1.5042 -1.5041 -1.4911 -1.4911 -1.4915   5  
8 -1.4992 -1.4993 -1.4986 -1.4986 -1.4984   2  

[5 rows x 49 columns]

#### Binary Classification

###### Feature Selection

In [9]:
# Do descision tree classification with positive and negative data in default arguments
# find feature importance and select important features

X = data_binary.iloc[:,:-1]
y = data_binary.iloc[:,-1].astype(int)
clf = RandomForestClassifier()
clf.fit(X, y)   
importance = clf.feature_importances_              # get feature importance

In [10]:
# summarize feature importance
for i,v in enumerate(importance):
    print('Feature: %0d, Score: %.5f' % (i,v))
    
# plot feature importance
plt.figure(figsize=(10,7))
plt.bar([x for x in range(len(importance))], importance)
plt.xlabel('Feature')
plt.ylabel('Importance')
plt.show()

Feature: 0, Score: 0.00061
Feature: 1, Score: 0.00205
Feature: 2, Score: 0.00035
Feature: 3, Score: 0.00085
Feature: 4, Score: 0.00449
Feature: 5, Score: 0.00030
Feature: 6, Score: 0.10977
Feature: 7, Score: 0.08512
Feature: 8, Score: 0.10209
Feature: 9, Score: 0.14378
Feature: 10, Score: 0.14206
Feature: 11, Score: 0.13885
Feature: 12, Score: 0.01409
Feature: 13, Score: 0.00712
Feature: 14, Score: 0.00162
Feature: 15, Score: 0.01372
Feature: 16, Score: 0.00554
Feature: 17, Score: 0.00558
Feature: 18, Score: 0.02066
Feature: 19, Score: 0.02584
Feature: 20, Score: 0.01933
Feature: 21, Score: 0.02488
Feature: 22, Score: 0.02251
Feature: 23, Score: 0.02039
Feature: 24, Score: 0.01509
Feature: 25, Score: 0.00031
Feature: 26, Score: 0.00035
Feature: 27, Score: 0.01042
Feature: 28, Score: 0.00039
Feature: 29, Score: 0.00036
Feature: 30, Score: 0.00398
Feature: 31, Score: 0.00335
Feature: 32, Score: 0.00342
Feature: 33, Score: 0.00943
Feature: 34, Score: 0.00921
Feature: 35, Score: 0.01006
Fe

In [21]:
#select the important features, i.e importance greater than 0.01
data_binary_new = data_binary.iloc[:, [6,7,8,9,10,11,12,15,18,19,20,21,22,23,24,27,35,48]]

###### Hyper parameter tuning

In [22]:
#define x and y
X = data_binary_new.iloc[:,:-1]
y = data_binary_new.iloc[:,-1].astype(int)

#split the data in to tran and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

#parameters for tuning
params = {
    "n_estimators":list(range(60,101,10)), 
    "criterion":("gini", "entropy"), 
    "min_samples_split":[2, 3, 4], 
    "min_samples_leaf":list(range(1,5)), 
}


clf = RandomForestClassifier(random_state=42)
tree_cv = GridSearchCV(clf, params, scoring="accuracy", n_jobs=-1, verbose=1, cv=3)
tree_cv.fit(X_train, y_train)
best_params = tree_cv.best_params_

pd.DataFrame(best_params.items(), columns=['Parameter', 'Best Value'])

Fitting 3 folds for each of 120 candidates, totalling 360 fits


Parameter Best Value
0          criterion    entropy
1   min_samples_leaf          1
2  min_samples_split          4
3       n_estimators         80

###### Training the model with best parameters

In [23]:
#train the model with random forest classifier with best parameter
clf_binary = RandomForestClassifier(**best_params)
clf_binary.fit(X_train, y_train)
print('')

###### Testing the model

In [24]:
pred = clf_binary.predict(X_train)
clf_report = pd.DataFrame(classification_report(y_train, pred, output_dict=True))
print("Train Result:\n================================================")
print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.2f}%")
print("_______________________________________________")
print(f"CLASSIFICATION REPORT:\n{clf_report}")
print("_______________________________________________")
print(f"Confusion Matrix: \n {confusion_matrix(y_train, pred)}\n")

Train Result:
Accuracy Score: 100.00%
_______________________________________________
CLASSIFICATION REPORT:
                0       1  accuracy  macro avg  weighted avg
precision     1.0     1.0       1.0        1.0           1.0
recall        1.0     1.0       1.0        1.0           1.0
f1-score      1.0     1.0       1.0        1.0           1.0
support    3005.0  2949.0       1.0     5954.0        5954.0
_______________________________________________
Confusion Matrix: 
 [[3005    0]
 [   0 2949]]



In [25]:
pred = clf_binary.predict(X_test)
clf_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
print("Test Result:\n================================================")
print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
print("_______________________________________________")
print(f"CLASSIFICATION REPORT:\n{clf_report}")
print("_______________________________________________")
print(f"Confusion Matrix: \n {confusion_matrix(y_test, pred)}\n")

Test Result:
Accuracy Score: 99.76%
_______________________________________________
CLASSIFICATION REPORT:
                     0            1  accuracy    macro avg  weighted avg
precision     0.999206     0.996136   0.99765     0.997671      0.997655
recall        0.996041     0.999225   0.99765     0.997633      0.997650
f1-score      0.997621     0.997678   0.99765     0.997649      0.997650
support    1263.000000  1290.000000   0.99765  2553.000000   2553.000000
_______________________________________________
Confusion Matrix: 
 [[1258    5]
 [   1 1289]]



#### Multi Class Classification

###### Feature Selection

In [26]:
# Do descision tree classification with positive labels in default arguments
# find feature importance and select important features

X = data_multi.iloc[:,:-1]
y = data_multi.iloc[:,-1].astype(int)
clf = RandomForestClassifier(random_state=42)
clf.fit(X, y)   
importance = clf.feature_importances_              # get feature importance

In [27]:
# summarize feature importance
for i,v in enumerate(importance):
    print('Feature: %0d, Score: %.5f' % (i,v))
    
# plot feature importance
plt.figure(figsize=(10,7))
plt.bar([x for x in range(len(importance))], importance)
plt.xlabel('Feature')
plt.ylabel('Importance')
plt.show()

Feature: 0, Score: 0.00347
Feature: 1, Score: 0.00639
Feature: 2, Score: 0.00082
Feature: 3, Score: 0.00376
Feature: 4, Score: 0.00798
Feature: 5, Score: 0.00045
Feature: 6, Score: 0.09958
Feature: 7, Score: 0.12054
Feature: 8, Score: 0.11179
Feature: 9, Score: 0.16420
Feature: 10, Score: 0.15486
Feature: 11, Score: 0.14215
Feature: 12, Score: 0.00870
Feature: 13, Score: 0.00307
Feature: 14, Score: 0.00276
Feature: 15, Score: 0.00984
Feature: 16, Score: 0.00342
Feature: 17, Score: 0.00159
Feature: 18, Score: 0.00963
Feature: 19, Score: 0.00844
Feature: 20, Score: 0.01048
Feature: 21, Score: 0.00984
Feature: 22, Score: 0.01239
Feature: 23, Score: 0.00637
Feature: 24, Score: 0.02822
Feature: 25, Score: 0.00073
Feature: 26, Score: 0.00030
Feature: 27, Score: 0.01378
Feature: 28, Score: 0.00053
Feature: 29, Score: 0.00035
Feature: 30, Score: 0.00747
Feature: 31, Score: 0.00663
Feature: 32, Score: 0.00464
Feature: 33, Score: 0.00707
Feature: 34, Score: 0.00657
Feature: 35, Score: 0.00781
Fe

In [28]:
#select important features, i.e importance greater than 0.01
data_multi_new = data_multi.iloc[:, [6,7,8,9,10,11,24,48]]

###### Hyper parameter tuning

In [29]:
#define x and y
X = data_multi_new.iloc[:,:-1]
y = data_multi_new.iloc[:,-1].astype(int)

#split the data in to tran and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

#parameters for tuning
params = {
    "n_estimators":list(range(60,101,10)), 
    "criterion":("gini", "entropy"), 
    "min_samples_split":[2, 3, 4], 
    "min_samples_leaf":list(range(1,5)), 
}


clf = RandomForestClassifier(random_state=42)
tree_cv = GridSearchCV(clf, params, scoring="accuracy", n_jobs=-1, verbose=1, cv=3)
tree_cv.fit(X_train, y_train)
best_params = tree_cv.best_params_
print(f"Best paramters: {best_params})")

Fitting 3 folds for each of 120 candidates, totalling 360 fits
Best paramters: {'criterion': 'entropy', 'min_samples_leaf': 1, 'min_samples_split': 4, 'n_estimators': 90})


###### Train the model with best parameters

In [32]:
#train the model with random forest classifier with best parameters
clf_multi = RandomForestClassifier(**best_params)
clf_multi.fit(X_train, y_train)
print('')

###### Testing the model

In [33]:
pred = clf_multi.predict(X_train)
clf_report = pd.DataFrame(classification_report(y_train, pred, output_dict=True))
print("Train Result:\n================================================")
print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.2f}%")
print("_______________________________________________")
print(f"CLASSIFICATION REPORT:\n{clf_report}")
print("_______________________________________________")
print(f"Confusion Matrix: \n {confusion_matrix(y_train, pred)}\n")

Train Result:
Accuracy Score: 99.93%
_______________________________________________
CLASSIFICATION REPORT:
               1           2           3           4           5  accuracy  \
precision    1.0    0.996503    1.000000    0.998888    1.000000  0.999326   
recall       1.0    1.000000    0.997768    1.000000    0.998638  0.999326   
f1-score     1.0    0.998249    0.998883    0.999444    0.999318  0.999326   
support    602.0  285.000000  448.000000  898.000000  734.000000  0.999326   

             macro avg  weighted avg  
precision     0.999078      0.999327  
recall        0.999281      0.999326  
f1-score      0.999179      0.999326  
support    2967.000000   2967.000000  
_______________________________________________
Confusion Matrix: 
 [[602   0   0   0   0]
 [  0 285   0   0   0]
 [  0   0 447   1   0]
 [  0   0   0 898   0]
 [  0   1   0   0 733]]



In [34]:
pred = clf_multi.predict(X_test)
clf_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
print("Test Result:\n================================================")
print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
print("_______________________________________________")
print(f"CLASSIFICATION REPORT:\n{clf_report}")
print("_______________________________________________")
print(f"Confusion Matrix: \n {confusion_matrix(y_test, pred)}\n")

Test Result:
Accuracy Score: 98.03%
_______________________________________________
CLASSIFICATION REPORT:
               1           2           3           4           5  accuracy  \
precision    1.0    0.959350    0.975000    0.961538    0.997006  0.980346   
recall       1.0    0.921875    0.960591    0.985915    0.994030  0.980346   
f1-score     1.0    0.940239    0.967742    0.973574    0.995516  0.980346   
support    251.0  128.000000  203.000000  355.000000  335.000000  0.980346   

             macro avg  weighted avg  
precision     0.978579      0.980397  
recall        0.972482      0.980346  
f1-score      0.975414      0.980282  
support    1272.000000   1272.000000  
_______________________________________________
Confusion Matrix: 
 [[251   0   0   0   0]
 [  0 118   2   7   1]
 [  0   1 195   7   0]
 [  0   2   3 350   0]
 [  0   2   0   0 333]]



#### Prediction

In [ ]:
# do binary classification, if output is zero update the output in csv as 'n'
# if the output is 1(positive) do multi class classification
# update output in the csv with labels p1, p2, p3, p4 or p5

In [67]:
test_data = pd.read_csv('test.csv')
test_data.head()

0         1         2         3         4         5         6  \
0 -4.520000e-06  0.000002  0.000134 -0.000017 -0.000002 -0.000003  0.027720   
1 -3.700000e-07  0.000002 -0.000007 -0.000002  0.000002  0.000001  0.025170   
2 -8.680000e-06 -0.000005 -0.000058 -0.000005  0.000010  0.000045  0.027690   
3 -3.890000e-06  0.000027 -0.000237  0.000019  0.000015  0.000877  0.018646   
4 -3.910000e-07 -0.000003  0.000005  0.000002  0.000009 -0.000012  0.019145   

          7         8         9  ...      38       39         40       41  \
0  0.027718  0.027584  0.027112  ...  3.9797 -0.62393   0.010489   5.6951   
1  0.025168  0.025175 -0.049183  ...  7.9604 -0.55811   9.603400  10.3340   
2  0.027695  0.027753 -0.026961  ...  8.1376 -0.70769   1.579500  10.5910   
3  0.018619  0.018856 -0.032315  ...  4.6469 -0.63897   0.852670   5.3556   
4  0.019149  0.019143  0.043739  ...  9.1222 -0.47616  41.988000   4.0899   

       42      43      44      45      46      47  
0 -1.5005 -1.5005 -1.5007 -1.4955 -1.4955 -1.4954  
1 -1.4974 -1.4974 -1.4973 -1.4974 -1.4973 -1.4973  
2 -1.4995 -1.4996 -1.4995 -1.4994 -1.4994 -1.4993  
3 -1.5076 -1.5077 -1.5068 -1.4963 -1.4962 -1.4967  
4 -1.4976 -1.4976 -1.4976 -1.4986 -1.4986 -1.4986  

[5 rows x 48 columns]

In [68]:
test_data['y'] = [0  for i in range(len(test_data))]    #define output column with dummy data

In [69]:
for i in range(len(test_data)):
    X = np.array(test_data.iloc[i, [6,11,12,15,22,35,39]]).reshape(1,7)
    y1 = clf_binary.predict(X)
    
    if y1 == 0:
        test_data.loc[i,'y'] = 'n'
    else:
        X = np.array(test_data.iloc[i, [6,8,9,10,22,23,24]]).reshape(1,7)
        y2 = clf_multi.predict(X)
        
        if y2 == 1:
            test_data.loc[i,'y'] = 'p1'
        elif y2 ==2:
            test_data.loc[i,'y'] = 'p2'
        elif y2 ==3:
            test_data.loc[i,'y'] = 'p3'
        elif y2 ==4:
            test_data.loc[i,'y'] = 'p4'
        elif y2 ==5:
            test_data.loc[i,'y'] = 'p5'  

In [70]:
test_data.head()

0         1         2         3         4         5         6  \
0 -4.520000e-06  0.000002  0.000134 -0.000017 -0.000002 -0.000003  0.027720   
1 -3.700000e-07  0.000002 -0.000007 -0.000002  0.000002  0.000001  0.025170   
2 -8.680000e-06 -0.000005 -0.000058 -0.000005  0.000010  0.000045  0.027690   
3 -3.890000e-06  0.000027 -0.000237  0.000019  0.000015  0.000877  0.018646   
4 -3.910000e-07 -0.000003  0.000005  0.000002  0.000009 -0.000012  0.019145   

          7         8         9  ...       39         40       41      42  \
0  0.027718  0.027584  0.027112  ... -0.62393   0.010489   5.6951 -1.5005   
1  0.025168  0.025175 -0.049183  ... -0.55811   9.603400  10.3340 -1.4974   
2  0.027695  0.027753 -0.026961  ... -0.70769   1.579500  10.5910 -1.4995   
3  0.018619  0.018856 -0.032315  ... -0.63897   0.852670   5.3556 -1.5076   
4  0.019149  0.019143  0.043739  ... -0.47616  41.988000   4.0899 -1.4976   

       43      44      45      46      47   y  
0 -1.5005 -1.5007 -1.4955 -1.4955 -1.4954  p4  
1 -1.4974 -1.4973 -1.4974 -1.4973 -1.4973   n  
2 -1.4996 -1.4995 -1.4994 -1.4994 -1.4993   n  
3 -1.5077 -1.5068 -1.4963 -1.4962 -1.4967   n  
4 -1.4976 -1.4976 -1.4986 -1.4986 -1.4986  p3  

[5 rows x 49 columns]