###### 1. Read an input string from user and check whether it is a palindrome or not using the stack data structure

In [93]:

input_string= input("Please enter the word: ")                 #input the word to the variable input_string
input_string= input_string.lower()                             #convert the word to lower letters

my_stack=[]                                                    #intilize a list my_stack, it can be used as a stack
check_string =''                                               #initialize an empty string, check_string


for i in input_string:                                         #append all values from the input_string to the list my_stack
    my_stack.append(i)

for i in range(len(my_stack)):                                 #pop a value from my_stack and add it to the check_string
    check_string = check_string + my_stack.pop()

    
if (check_string==input_string):                              #if check_string is equal to input_string 
    print('The word entered is a palindrome')                 #the given word is a palindrome else it is not a palindrome

else:
    print('The word entered is not a palindrome')

    

Please enter the word: malayalam
The word entered is a palindrome


###### 2. Read lines from the file ‘1.txt’, sort the lines in natural sort order using the third letter of each line and finally write the sorted result to a file ‘1_out.txt’

In [61]:
#open the file 1.txt as file_1
file_1 = open('1.txt', mode='r+')

#print all the lines
for line in file_1:
    print(line, end='')


January
February
March
April
May
June
July
August
September
October
November
December


In [66]:
#define a function which return third letter of a string 
def third_letter(string):
        return string[2]

file_1 = open('1.txt', mode='r+')     #open the '1.txt'
lines_list = file_1.readlines()        #read all lines and save it to a list
lines_list.sort(key=third_letter)


#open the file '1_Out.txt'
file_2= open('1_Out.txt', mode='w+')

#Write the soarted list to the file uning file.write() command
for i in range(len(lines_list)):
    file_2.write(lines_list[i])


In [67]:
#open the file '1_Out.txt' for checking sorted list is written to it
file_2= open('1_Out.txt', mode='r')

#print the lines that wrote to the file '1_Out.txt'
for line in file_2:
    print(line, end='')

February
December
August
July
January
June
September
March
April
October
November
May


In [68]:
#close the file '1.txt' and file '1_Out.txt'
file_1.close()
file_2.close()

###### 3. Write a higher order function that has a formal parameter ‘mode’ of type int. If mode is ‘1’, this function should return a lambda function that converts a passed in temperature from Celsius to Fahrenheit and if mode is ‘2’ the higher order function should return a lambda function that converts a passed in temperature from Fahrenheit to Celsius. Call the higher order function for both modes and use the returned functions to convert 58 degrees Celsius to Fahrenheit and 58 degrees Fahrenheit to Celsius

In [2]:
#define function for converting temparature
def temp_converter(mode, temp):
    
    if mode==1:                                            #if mode=1 convert temp to fahrenheit
        return (lambda temp: (temp*(9/5))+32)(temp)        #fahrenheit=(celcius*(9/5))+32
    elif mode==2:                                          #if mode=2 convert temp to celcius
        return (lambda temp: (temp-32)*(5/9))(temp)        #celcius= (fahrenheit-32)*(5/9)

    
while True:                                                #execute the block continously
    mode= int(input("1 for celcius to fahrenheit, 2 for fahrenheit to celcius, 0 for end the process:")) #enter the mode value

    if mode==1:                                                                   #if mode=1 conversion is from celcius to fahrenheit
        temp= float(input("Please enter the value of temperature in celcius:"))
        print("Temperature in Fahrenheit:{:.2f}\n".format(temp_converter(1,58)))
    elif mode==2:                                                                 #if mode=2 conversion is from fahrenheit to celcius
        temp= float(input("Please enter the value of temperature in fahrenheit:"))
        print("Temperature Celsius:{:.2f}\n".format(temp_converter(2,58)))
    elif mode==0:
        break
    else:
        print("Please enter 1 or 2")

1 for celcius to fahrenheit, 2 for fahrenheit to celcius, 0 for end the process:1
Please enter the value of temperature in celcius:58
Temperature in Fahrenheit:136.40

1 for celcius to fahrenheit, 2 for fahrenheit to celcius, 0 for end the process:2
Please enter the value of temperature in fahrenheit:58
Temperature Celsius:14.44

1 for celcius to fahrenheit, 2 for fahrenheit to celcius, 0 for end the process:0


###### 4. Create a 4x4 matrix (list of lists) with random positive integer values using list comprehension. Use this matrix and list comprehension to create a new matrix such that even numbers remain unchanged, but odd numbers get incremented by 1

In [1]:

import numpy as np                                                  #import library numpy

col = int(input("Please enter the number of columns "))             #enter number of columns to variable col
row = int(input("Please enter the number of rows "))                #enter number of rows to the variable row

my_matrix = np.array([[np.random.randint(1,10)                      #np.array() transform list of list to array
                       for i in range(col)] for j in range(row)])   #np.random.randint(1,10) assign random values 
                                                                    #between 1 and 10                
                                                                                              
print("\nInitial matrix:")
print(my_matrix,"\n")                                               #print initial matrix

                                                                    #if the number is even (reminder = 0 while dividing with 2) 
                                                                    #retain the number,#else increment by 1        

new_matrix= np.array([[my_matrix[j,i] if (my_matrix[j,i]%2==0)         
                       else my_matrix[j,i]+1 for i in range(col)] for j in range(row)]) 

print("Updated matrix:")                                            #print updated matrix
print(new_matrix)


Please enter the number of columns 4
Please enter the number of rows 4

Initial matrix:
[[7 9 6 8]
 [7 3 2 1]
 [1 7 1 7]
 [9 6 7 7]] 

Updated matrix:
[[ 8 10  6  8]
 [ 8  4  2  2]
 [ 2  8  2  8]
 [10  6  8  8]]


###### 5.Read lines from files ‘5_1.txt’ and ‘5_2.txt’, find out the words that are present in file ‘5_2.txt’ but not in file ‘5_1.txt’ and finally write the result to a file named ‘5_out.txt’

In [86]:
#open file '5_1.txt' and '5_2.txt' as read, write
#create a new file '5_out.txt'

file_1 = open('5_1.txt', mode='r+')
file_2= open('5_2.txt', mode='r+')
file_out = open('5_out.txt', mode='w+')

#save lines from file_1 and file_2 in the seperate lists
file1_lines = file_1.readlines()
file2_lines = file_2.readlines()

#check lines from file_2 not present in the file_1
#if so write the line file_out
for line in file2_lines:
    if(line not in file1_lines): 
        file_out.write(line)


In [87]:
#close all files
file_1.close()
file_2.close()
file_out.close()